# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 054ae5aefc25ceaf49df716e74f7570a289efbb303804bef4521dd9dad36ef2238fd9bea3800f9da5bcd8655fc315394a68602faa68967bede4806c23745ca19

test:
  secret_key_base: 4507b63cd226be51e8ac8dd5a30d9669f447261541c63dd2723cd441e05e31ef5cac65a56c6b8aa44900e1419d8b1c6608a915a0c42b8d9af6c79d220e9501bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
